### ISSUE TITLE
can't get a good result.

### ISSUE THREAD

**Issue by FirstPotato** [mattdutson/xview2#1]
Hi there, I've run your code but I can't get clear segmentation results.
I want to know what hyperparameters did you use, like epoch. Because I trained 50 epochs but got bad results.
And I can't adjust batchsize so the model can't feed my GPU enough, I want to trained faster.

I didn't join the chanllenge and I just want to get good results for my research.
Thank you.

**Comment by mattdutson** [comment]
Yeah the hyperparameters in the repo may not be updated with the values that gave good results. I’ll update it when I get home this afternoon.

Matt Dutson

On Dec 18, 2019, at 1:34 AM, FirstPotato <notifications@github.com> wrote:

﻿

Hi there, I've run your code but I can't get clear segmentation results.
I want to know what hyperparameters did you use, like epoch. Because I trained 50 epochs but got bad results.
And I can't adjust batchsize so the model can't feed my GPU enough, I want to trained faster.

I didn't join the chanllenge and I just want to get good results for my research.
Thank you.

**Comment by mattdutson** [comment]
Turns out the only thing that needed updating was the class weight array. Pushed this change.

For specifics on how we obtained our results see [this link](https://mdutson.net/assets/xview2_report.pdf).
